package com.bookofbrains.shareapp.models

data class Hobby(val title: String)

object Supplier {
    val hobbies = listOf(
            Hobby("Acrobatics"),
            Hobby("Acroyoga"),
            Hobby("Acting"),
            Hobby("Action Figures"),
            Hobby("African Djembe"),
            Hobby("Aikido"),
            Hobby("Airplane Combat"),
            Hobby("Airplane Flight"),
            Hobby("Amateur Geology"),
            Hobby("Animation"),
            Hobby("Antiques"),
            Hobby("Arcade Games"),
            Hobby("Archery"),
            Hobby("Architecture"),
            Hobby("Astral Projection"),
            Hobby("Astrology"),
            Hobby("Astronomy"),
            Hobby("Audiophile"),
            Hobby("Autograph Collecting"),
            Hobby("Automobile Restoration"),
            Hobby("Autoracing"),
            Hobby("Backpacking Travel"),
            Hobby("Badminton"),
            Hobby("Ball and Jacks"),
            Hobby("Ballet"),
            Hobby("Banjo"),
            Hobby("Bartending"),
            Hobby("Base Jumping"),
            Hobby("Bass Guitar"),
            Hobby("Beat Box"),
            Hobby("Beer Brewing"),
            Hobby("Beer Tasting"),
            Hobby("Billiards / Pool"),
            Hobby("Birdwatching"),
            Hobby("Blues"),
            Hobby("Board Games"),
            Hobby("Bodybuilding"),
            Hobby("Bowling"),
            Hobby("Boxing"),
            Hobby("Break Dancing"),
            Hobby("Bridge"),
            Hobby("Calligraphy"),
            Hobby("Camping"),
            Hobby("Candle Making"),
            Hobby("Capoeira"),
            Hobby("Car Collecting"),
            Hobby("Card Games"),
            Hobby("Card Tricks"),
            Hobby("Cardio Workout"),
            Hobby("Cats"),
            Hobby("Ceramics / Pottery"),
            Hobby("Cheese Tasting"),
            Hobby("Chess"),
            Hobby("Cigar Smoking and Rolling"),
            Hobby("Classical"),
            Hobby("Cliff Diving"),
            Hobby("Coffee Roasting"),
            Hobby("Coin Collecting"),
            Hobby("Comic Books"),
            Hobby("Competitive Eating"),
            Hobby("Compose Music"),
            Hobby("Concert Posters"),
            Hobby("Conga / Bongo"),
            Hobby("Cooking"),
            Hobby("Crochet"),
            Hobby("Croquet"),
            Hobby("Cycling"),
            Hobby("Diving"),
            Hobby("DJ"),
            Hobby("Dogs"),
            Hobby("Doll Collecting"),
            Hobby("Dominoes"),
            Hobby("Drum Set"),
            Hobby("Fashion Design"),
            Hobby("Fencing"),
            Hobby("Ferrets"),
            Hobby("Film Making"),
            Hobby("Fine Art Collecting"),
            Hobby("Fishing"),
            Hobby("Fishkeeping"),
            Hobby("Floristry"),
            Hobby("Fly Fishing"),
            Hobby("Foosball"),
            Hobby("Freelance Writing")
    )
}